version: 2

models:
  - name: dim_client
    columns:
      - name: dim_client_id
        tests: [unique, not_null]
      - name: client
        tests: [not_null]

  - name: dim_date
    columns:
      - name: dim_date_id
        tests: [unique, not_null]
      - name: date_complete
        tests: [unique, not_null]

  - name: fct_tickets
    columns:
      - name: ticket_id
        tests: [unique, not_null]
      - name: dim_client_id
        tests:
          - relationships:
              arguments:
                to: ref('dim_client')
                field: dim_client_id
      - name: dim_date_creation_id
        tests:
          - relationships:
              arguments:
                to: ref('dim_date')
                field: dim_date_id